name: Build Checking on the LMS

on:
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Uses Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup npm
        run: |
          npm install
      - name: Generate prisma
        run: npx prisma generate
      - name: Build Checking
        run: npm build
